name: dashboard
channels:
  - default
dependencies:
  # default
  - jupyter>=1.0.0
  - pathlib
  - pip>=23.2.1
  - plotly
  - python
  - pyyaml
  - sqlalchemy>=1.4.0,<2.0.0
  - statsmodels
  - watchdog
