name: dashboard
channels:
  - default
dependencies:
  # conda-forge only
  - conda-forge::glom
  - conda-forge::hiredis>=2.1.1
  - conda-forge::optuna
  - conda-forge::optuna-dashboard
  - conda-forge::paho-mqtt>=1.6.1
  - conda-forge::pandas-ta
  - conda-forge::pika>=1.3.1
  - conda-forge::pycoingecko>=3.1.0
  - conda-forge::pydantic==1.10.4
  - conda-forge::streamlit==1.24.1
  - conda-forge::ujson>=5.7.0
  - pip>=23.2.1
  - pip:
      - commlib-py
      - defillama
      - st-pages
      - streamlit-ace
      - streamlit-elements==0.1.*
      - git+https://github.com/hummingbot/hbot-remote-client-py.git  # This could be a hummingbot channel conda package
      - git+https://github.com/hummingbot/docker-manager.git  # This could be a hummingbot channel conda package
