name: dashboard
channels:
  - default
dependencies:
  - python
  - streamlit
  - watchdog
  - plotly
  - sqlalchemy
  - statsmodels
  - pyyaml
  - jupyter
  - pathlib
  - pip
  - pip:
      - pycoingecko
      - glom
      - defillama
      - pandas_ta
      - commlib-py
      - optuna
      - optuna-dashboard
      - streamlit-ace
      - st-pages
      - streamlit-elements==0.1.*
      - git+https://github.com/hummingbot/hbot-remote-client-py.git
      - git+https://github.com/hummingbot/docker-manager.git
